DATA_ROOT: Dataset
OUT_DIR: artifacts/refweaveformer_yolo_fast

IMG_SIZE: 256
NUM_CLASSES: 1
CLASS_NAMES:
  - Defect

EPOCHS: 50
BATCH_SIZE: 1
NUM_WORKERS: 0

LR: 0.00002
MIN_LR: 0.000001
WEIGHT_DECAY: 0.0001

CONF_THRES: 0.25
NMS_IOU: 0.50
MAX_DET: 300

VAL_FRAC: 0.15
TEST_FRAC: 0.15
SEED: 42
AMP: true
PATIENCE: 5
SAVE_EVERY: 5

BOX_WEIGHT: 7.5
OBJ_WEIGHT: 1.0
CLS_WEIGHT: 1.5
AUX_WEIGHT: 0.35
